service: test-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: us-west-2
  environment: ${file(./env_var.yml)}

functions:
  login:
    handler: handlers/login.handler
    events:
      - http: 
          path: /login
          method: get
  register:
    handler: handlers/register.handler
    events:
      - http: 
          path: /register
          method: post
  getAllRecipes:
    handler: handlers/getAllRecipes.handler
    events:
      - http: 
          path: /get-all-recipes
          method: get
  